### ISSUE TITLE
Twigified needs to be installed to themes/twiggy

### ISSUE THREAD

**Issue by fabianx-ai** [jenlampton/twiggy#1]
Twigified needs to be installed to themes/twiggy else it gives fatal error.

**Comment by jenlampton** [comment]
I renamed the github project, and the theme.  Hopefully that does the trick :)

**Comment by fabianx-ai** [comment]
Yup, and a comment on the README would be good, because sites/default/themes/twiggy does not work, while themes/twiggy does. (and yes that is probably something we need to fix in Drupal for embed / extends tag).
